// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrialBalanceWebApp.Data;

#nullable disable

namespace TrialBalanceWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221018103039_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrialBalanceWebApp.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankAccount")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("OpeningBalanceId")
                        .HasColumnType("integer");

                    b.Property<int>("RevenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("OpeningBalanceId")
                        .IsUnique();

                    b.HasIndex("RevenueId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.AccountClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("AccountClasses");
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Active")
                        .HasColumnType("double precision");

                    b.Property<double>("Passive")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.Revenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Credit")
                        .HasColumnType("double precision");

                    b.Property<double>("Debit")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Revenues");
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.Account", b =>
                {
                    b.HasOne("TrialBalanceWebApp.Models.AccountClass", null)
                        .WithMany("Accounts")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrialBalanceWebApp.Models.Balance", "OpeningBalance")
                        .WithOne()
                        .HasForeignKey("TrialBalanceWebApp.Models.Account", "OpeningBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrialBalanceWebApp.Models.Revenue", "Revenue")
                        .WithOne()
                        .HasForeignKey("TrialBalanceWebApp.Models.Account", "RevenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpeningBalance");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.AccountClass", b =>
                {
                    b.HasOne("TrialBalanceWebApp.Models.Bank", null)
                        .WithMany("AccountClasses")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.AccountClass", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("TrialBalanceWebApp.Models.Bank", b =>
                {
                    b.Navigation("AccountClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
